services:
  nginx:
    image: nginx:1.31.0
    container_name: gitea-nginx
    networks:
      default:
        aliases:
          - gitea
      entry-net:
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - gitea

  gitea:
    image: gitea/gitea:1.26.1-rootless
    container_name: gitea
    restart: always
    environment:
      - GITEA__server__DOMAIN=${DOMAIN:-localhost}
      - GITEA__server__ROOT_URL=${ROOT_URL:-http://localhost:3000}
      - GITEA__server__SSH_DOMAIN=${SSH_DOMAIN:-localhost}
      - GITEA__server__SSH_PORT=22
      - GITEA__server__START_SSH_SERVER=false
      - GITEA__server__SSH_CREATE_AUTHORIZED_KEYS_FILE=false
      - GITEA__server__DISABLE_SSH=false
    volumes:
      - gitea-config:/etc/gitea:rw
      - gitea-data:/var/lib/gitea:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

volumes:
  gitea-config:
  gitea-data:

networks:
  default:
    name: gitea-net
  entry-net:
    name: entry-net
    external: true
